

import com.gmatsu.models.Elevator
import com.gmatsu.models.Clock
import com.gmatsu.models.Direction
import com.gmatsu.models.Passenger
import com.gmatsu.models.*

declare Request
   @role(event)
   @expires(1s)
end

declare Clock
   @role(event)
   @expires(1s)
end


dialect "mvel"


rule "Passenger Request Entered"
no-loop true
when
    $request: Request() from entry-point "RequestStream"
then
   // hail elevators?
   System.out.println("request recieved");
   Passenger p = new Passenger();
   p.setToFloor($request.getToFloor());
   p.setFromFloor($request.getFromFloor());
   p.setMyElevator(null);
   insert(p);

end

query "FetchPassengers"()
    $p : Passenger()
end


//Passenger Enters Elevator



// Passenger Floor is reached
rule "Passenger Floor is reached"
when

then
 end

// Passenger Exits System





// ------ Elevator Rules

// Fetch List of Active Elevtors in system
query "FetchElevators"()
    $elevator : Elevator()
end


//Kick the Elevetors to do something , Transition it to a new floor.
rule "Increment Elevator Location"
//no-loop true
when
	$c : Clock() from entry-point "IntervalStepStream"
	$elevator : Elevator ()
then
//    System.out.println("Elevetor moving :"+ $elevator.getCurrentFloor() + " : "+$c);

	int floorDiff = 0;
    if($elevator.getDirection() == Direction.UP)  floorDiff = 1;
    else if ($elevator.getDirection() == Direction.DOWN) floorDiff = -1;

    if($elevator.getCurrentFloor() + floorDiff >= $elevator.getMaxFloor()) floorDiff = 0;

    //update the elevators floor
	modify($elevator) {
	    currentFloor = $elevator.getCurrentFloor() + floorDiff,
		evaluating= false
	}

	retract($c)
	
end

//  Init -> CLose state

//  Close -> Open State

// Open -> close State

// Moving ?

// stopped ?


rule "Waiting elevetor is hailed"
when
    $p : Passenger(myElevator == null)
    $e: Elevator(direction == Direction.NONE)
    eval( Math.abs( $p.fromFloor - $e.currentFloor) < 4 )
then
    //Found a close by Elevator
     System.out.println("Found an elevator");
     //hail it
     	int floorDiff = 0;
     if($p.getFromFloor() - $e.getCurrentFloor() < 0)  floorDiff = -1;   //request below
     else if ($p.getFromFloor() - $e.getCurrentFloor() > 0) floorDiff = 1; //request above

     Direction dir = (floorDiff == 1)? Direction.UP: Direction.DOWN;

     //set in motion
     modify($e){
        direction = dir

     }


 end


rule "Passenger wants off, so open the door"
when
    //Not processing elevator, and door isn't open, and its active, and passenger wants off this floor
    $elevator : Elevator(evaluating == false , doorState != DoorState.OPEN)
    exists Passenger(myElevator == $elevator, toFloor == $elevator.currentFloor)
then

    // open the door
    modify($elevator) {
        doorState = DoorState.OPEN,
        evaluating = true,
        tripCount = 1  //need to increment
    }
    
end

 // Door is open, and passengers are waiting, and going in the same direction as the elevator
 // Door is open, and passnagers are waiting, elevator has not direction



rule "Close The Door When Finished Processing"
when
    $elevator : Elevator (evaluating == false, doorState == DoorState.OPEN)
	not Passenger ($elevator == $elevator, toFloor == $elevator.currentFloor)
then
    //no one in this elevator wants off, and the door is open.. close it dammit
    modify($elevator){
        doorState = DoorState.CLOSE,
        evaluating = true
    }
    
end

// Elevator on same floor as request
// Elevator heading down,  has a request
// Elevator heading up,  has a request



rule "Put an Empty Elevator needing Maintenance out of Order"
when
    $elevator: Elevator(passengers.size ==0 , tripCount >100)
then
    modify($elevator){
        maintenance = Maintenance.INACTIVE,
        tripCount = 0
    }
end







